import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { NextAuthProvidr } from "./Providers";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvidr>
        <body className={lexend.className}>{children}</body>
      </NextAuthProvidr>
    </html>
  );
}
